In [1]:
import numpy as np

In [44]:
list_h1 = [1,2,3,4]
list_h2 = [[1,2,3,4]]
list_v = [[1],
          [2],
          [3],
          [4]]


In [48]:
print(list_h1)
print(list_h2)
print(list_v)

[1, 2, 3, 4]
[[1, 2, 3, 4]]
[[1], [2], [3], [4]]


In [64]:
vector_h1 = np.array(list_h1, ndmin=2)
vector_h2 = np.array(list_h2)
vector_v = np.array(list_v, dtype=object)



In [65]:
print(vector_h1)
print(vector_h2)
print(vector_v)

[[1 2 3 4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [66]:
print(vector_h1.T)
print(vector_h2.T)
print(vector_v.T)

[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [69]:
vector_h1.dot(vector_h1.T)

array([[30]])

In [20]:
b.dot(a)

array([30])

In [25]:
a.dot(b.T)

array([30])

In [22]:
np.dot(a,a)

30

In [24]:
np.dot(b,a)

array([30])

In [55]:
np.matrix([list_h1, list_h1, list_h1])

matrix([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [60]:
np.matrix([vector_h1,vector_h1])

matrix([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [62]:
np.matrix([vector_h2.T,vector_h2.T])

ValueError: matrix must be 2-dimensional