In [70]:
import numpy as np

In [112]:
list_h1 = [0.00000001,1,2,3,400000]
list_h2 = [[0,1,2,3,4]]
list_v = [[0],
          [1],
          [2],
          [3],
          [4]]


In [113]:
print(list_h1)
print(list_h2)
print(list_v)

[1e-08, 1, 2, 3, 400000]
[[0, 1, 2, 3, 4]]
[[0], [1], [2], [3], [4]]


In [114]:
vector_h1 = np.array(list_h1, ndmin=2)
vector_h2 = np.array(list_h2)
vector_v = np.array(list_v, dtype=object)



In [115]:
print(vector_h1)
print(vector_h2)
print(vector_v)

[[1.e-08 1.e+00 2.e+00 3.e+00 4.e+05]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [116]:
print(vector_h1.T)
print(vector_h2.T)
print(vector_v.T)

[[1.e-08]
 [1.e+00]
 [2.e+00]
 [3.e+00]
 [4.e+05]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]


In [117]:
vector_h1.dot(vector_h1.T)

array([[1.6e+11]])

In [118]:
np.log(vector_h1)

array([[-18.42068074,   0.        ,   0.69314718,   1.09861229,
         12.89921983]])

In [119]:
np.exp(-vector_h1)

array([[0.99999999, 0.36787944, 0.13533528, 0.04978707, 0.        ]])

In [120]:
np.add(vector_h1,4)

array([[4.00000001e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00,
        4.00004000e+05]])