In [163]:
import numpy as np

In [164]:
list_h1 = [0.,1,2,3,4]
list_h2 = [[0,1,2,3,4]]
list_v = [[0],
          [1],
          [2],
          [3],
          [4]]


In [125]:
print(list_h1)
print(list_h2)
print(list_v)

[0.0, 1, 2, 3, 4]
[[0, 1, 2, 3, 4]]
[[0], [1], [2], [3], [4]]


In [158]:
vector_h1 = np.array(list_h1, ndmin=2)
vector_h2 = np.array([list_h1,list_h1,list_h1,list_h1,list_h1])
vector_v = np.array(list_v, dtype=int)



In [115]:
print(vector_h1)
print(vector_h2)
print(vector_v)

[[1.e-08 1.e+00 2.e+00 3.e+00 4.e+05]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [116]:
print(vector_h1.T)
print(vector_h2.T)
print(vector_v.T)

[[1.e-08]
 [1.e+00]
 [2.e+00]
 [3.e+00]
 [4.e+05]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]


In [117]:
vector_h1.dot(vector_h1.T)

array([[1.6e+11]])

In [118]:
np.log(vector_h1)

array([[-18.42068074,   0.        ,   0.69314718,   1.09861229,
         12.89921983]])

In [122]:
np.exp(-vector_h1)

array([[0.99999999, 0.36787944, 0.13533528, 0.04978707, 0.        ]])

In [120]:
np.add(vector_h1,4)

array([[4.00000001e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00,
        4.00004000e+05]])

In [127]:
vector_h1

array([[0., 1., 2., 3., 4.]])

In [128]:
vector_h1.shape

(1, 5)

In [129]:
vector_h1.shape[0]

1

In [130]:
vector_h1.shape[1]

5

In [131]:
input = np.array([[1,2,3], [3,4,5]], ndmin=2)

In [132]:
input.shape

(2, 3)

In [134]:
np.exp(-input)

array([[0.36787944, 0.13533528, 0.04978707],
       [0.04978707, 0.01831564, 0.00673795]])

In [155]:
vector_v

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [159]:
vector_h2

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [162]:
vector_h1.T * vector_h2

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [165]:
np.divide(vector_h2, vector_h1)

/tmp/ipykernel_459267/1938981443.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(vector_h2, vector_h1)


array([[nan,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.]])

In [177]:
matrix = np.array([list_h1,list_h1,list_h1,list_h1,list_h1])
list = [1,2,3,4,5]
vector = np.array(list)

In [178]:
print(matrix)
print(vector)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[1 2 3 4 5]


In [179]:
np.divide(matrix, vector)

array([[0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.        , 0.5       , 0.66666667, 0.75      , 0.8       ]])

In [180]:
np.divide(5, vector)

array([5.        , 2.5       , 1.66666667, 1.25      , 1.        ])

In [181]:
np.add(matrix, 5)

array([[5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.]])

In [182]:
np.add(matrix, matrix)

array([[0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.]])

In [183]:
np.add(matrix, vector)

array([[1., 3., 5., 7., 9.],
       [1., 3., 5., 7., 9.],
       [1., 3., 5., 7., 9.],
       [1., 3., 5., 7., 9.],
       [1., 3., 5., 7., 9.]])

In [184]:
np.add(vector, 5)

array([ 6,  7,  8,  9, 10])

In [185]:
np.add(vector, vector)

array([ 2,  4,  6,  8, 10])