In [70]:
import numpy as np

In [124]:
list_h1 = [0.,1,2,3,4]
list_h2 = [[0,1,2,3,4]]
list_v = [[0],
          [1],
          [2],
          [3],
          [4]]


In [125]:
print(list_h1)
print(list_h2)
print(list_v)

[0.0, 1, 2, 3, 4]
[[0, 1, 2, 3, 4]]
[[0], [1], [2], [3], [4]]


In [126]:
vector_h1 = np.array(list_h1, ndmin=2)
vector_h2 = np.array(list_h2)
vector_v = np.array(list_v, dtype=object)



In [115]:
print(vector_h1)
print(vector_h2)
print(vector_v)

[[1.e-08 1.e+00 2.e+00 3.e+00 4.e+05]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [116]:
print(vector_h1.T)
print(vector_h2.T)
print(vector_v.T)

[[1.e-08]
 [1.e+00]
 [2.e+00]
 [3.e+00]
 [4.e+05]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]


In [117]:
vector_h1.dot(vector_h1.T)

array([[1.6e+11]])

In [118]:
np.log(vector_h1)

array([[-18.42068074,   0.        ,   0.69314718,   1.09861229,
         12.89921983]])

In [122]:
np.exp(-vector_h1)

array([[0.99999999, 0.36787944, 0.13533528, 0.04978707, 0.        ]])

In [120]:
np.add(vector_h1,4)

array([[4.00000001e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00,
        4.00004000e+05]])

In [127]:
vector_h1

array([[0., 1., 2., 3., 4.]])

In [128]:
vector_h1.shape

(1, 5)

In [129]:
vector_h1.shape[0]

1

In [130]:
vector_h1.shape[1]

5

In [131]:
input = np.array([[1,2,3], [3,4,5]], ndmin=2)

In [132]:
input.shape

(2, 3)

In [134]:
np.exp(-input)

array([[0.36787944, 0.13533528, 0.04978707],
       [0.04978707, 0.01831564, 0.00673795]])